version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing...
  pre_build:
    commands:
      - echo Preparing build...
  build:
    commands:
      - echo Building site...
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync . s3://syedfawad-static-website --delete --exclude ".git/*" --exclude "buildspec.yml"
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id E3U4BDK0QJVQJ9 --paths "/*"
      - echo Deployment and invalidation complete.

artifacts:
  files:
    - '**/*'
